# Use Node.js as the base image
FROM node:18
 
# Set the working directory
WORKDIR /usr/src/app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the application code
COPY . .
 
# Expose the application port
EXPOSE 3002
 
# Start the application
CMD ["npm", "start"]
