name: Destroy the AWS infrastructure.
run-name: Destroy AWS Infra
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy AWS EC2 Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.10.3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Remove Terraform cache and initialize
        run: |
          cd ./infra/environments/dev
          rm -rf .terraform
          terraform init -var-file="dev.tfvars"
       
      # Run Terraform Destroy to tear down the resources
      - name: Terraform Destroy
        run: |
         cd ./infra/environments/dev
         terraform destroy -var-file="dev.tfvars" -auto-approve

    
